version: "3.9"

services:
  api:
    container_name: api
    build:
      target: development
      context: ./api
      dockerfile: Dockerfile
    networks:
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/api
    tty: true
    stdin_open: true
    command: npm run start:dev
    ports:
      - "3002:3001"
      - "9229:9229"
  webapp:
    container_name: webapp
    build:
      target: development
      context: ./webapp
      dockerfile: Dockerfile
    networks:
      - webapp
    environment:
      - NODE_ENV=development
    volumes:
      - ./webapp:/webapp
    depends_on:
      - api
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"

networks:
  api:
    name: api-network-fuds-tracker
  webapp:
    name: webapp-network-fuds-tracker
