version: "3.9"

services:
  dev-redis:
    container_name: dev-redis
    image: redis:7.0.9-alpine
    ports:
      - "${DEV_REDIS_PORT}:6379"
    volumes:
      - dev-redis:/data

  tests-redis:
    container_name: tests-redis
    image: redis:7.0.9-alpine
    ports:
      - "${TEST_REDIS_PORT}:6379"
    volumes:
      - dev-redis:/data

  mailslurper:
    container_name: mailslurper
    image: marcopas/docker-mailslurper
    ports:
      - "2500:2500"
      - "9000:8080"
      - "8085:8085"

  tests-database:
    image: postgres:14.5-alpine
    restart: always
    container_name: tests-database
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}

  dev-database:
    image: postgres:14.5-alpine
    container_name: dev-database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    ports:
      - "${DEV_POSTGRES_PORT}:5432"
    volumes:
      - dev-database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DEV_POSTGRES_USER}", "-d", "${DEV_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dev-database:
    driver: local
  dev-redis:
    driver: local
