version: "3.9"

services:
  database:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - api
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  api:
    container_name: api
    build:
      target: development
      context: ./api
      dockerfile: Dockerfile
    networks:
      - api
      - webapp
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/api
      - /api/node_modules
    tty: true
    stdin_open: true
    env_file:
      - ./api/.env
    command: npm run start:dev
    depends_on:
      - database
    ports:
      - ${API_PORT}:${API_PORT}
      - "9229:9229"
  webapp:
    container_name: webapp
    build:
      target: development
      context: ./webapp
      dockerfile: Dockerfile
    networks:
      - webapp
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./webapp:/webapp
    depends_on:
      - api
    tty: true
    stdin_open: true
    env_file:
      - ./webapp/.env
    ports:
      - "5173:5173"

networks:
  api:
  webapp:

volumes:
  mongo_data:
