name: Post PR Deployment
on:
  push:
    branches:
      - master
jobs:
  merged_to_master:
    name: CD-app
    runs-on: self-hosted
    env:
      VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
      VITE_LOG_ROCKET_KEY: ${{ secrets.VITE_LOG_ROCKET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install:deployment
      - run: pnpm prisma:generate
      - run: pnpm build
      - run: pm2 restart webserver
