name: Post PR Deployment
on:
  push:
    branches:
      - master
jobs:
  merged_to_master:
    name: CD-app
    runs-on: self-hosted
    env:
      VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install:deployment
      - run: pnpm prisma:generate
      - run: pnpm build
      - run: pnpm prisma:migrate:deploy
      - run: cp ~/actions-runner/_work/funds-tracker/funds-tracker/webapp/dist ~/app/webapp -r
      - run: cp ~/actions-runner/_work/funds-tracker/funds-tracker/webserver/dist ~/app/webserver -r
      - run: cp ~/actions-runner/_work/funds-tracker/funds-tracker/webserver/node_modules ~/app/webserver -r
      - run: pm2 restart webserver
