name: Post PR Deployment
on:
  push:
    branches:
      - master
jobs:
  merged_to_master:
    name: CD-app
    runs-on: self-hosted
    steps:
      - run: docker compose -f docker-compose.production.yml up -d
