name: Continuous integration
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  static-analysis:
    runs-on: ubuntu@22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.x
      - run: pnpm install
      - run: pnpm test:all
      - run: pnpm lint:all
